### ISSUE TITLE
Celluloid::Future retaining arguments causing them to not get GC'd

### ISSUE THREAD

**Issue by jonhyman** [celluloid/celluloid#463]
I'm not sure if this is a bug with Ruby (I'm on ruby 2.1.2p95 but the same behavior exists on 2.0.0.-p247) or Celluloid, but due to a memory leak with Futures we can't use Celluloid at all for our use case because memory can grow unbounded quickly and uses up all the RAM on the machine. I've tested 0.15.2 and 0.16.0 and it appears on both. Here's a very simple repro:

``` ruby
# Setup
require 'celluloid'

def Process.rss ; `ps -o rss= -p #{Process.pid}`.chomp.to_i ; end
def Process.pretty_rss ; Process.rss.to_s.gsub(/(\d)(?=(\d{3})+(\..*)?$)/,'\1,') + " kilobytes" ; end

class Foo
  include Celluloid
  def do_something(arg1)
    return true
  end
end
```

Storing futures in an array, then iterating back over them causes unbounded memory growth:

``` ruby
puts(Process.pretty_rss)
20.times do
  f = Foo.new
  futures = []
  100.times { futures << f.future.do_something("a" * 50_000) }
  futures.length.times {|i| futures[i].value }
  f.terminate()
  futures = []
  puts(Process.pretty_rss)
end

# => 28,384 kilobytes
# => 33,824 kilobytes
# => 39,624 kilobytes
# => 43,396 kilobytes
# => 48,128 kilobytes
# => 53,320 kilobytes
# => 55,900 kilobytes
# => 56,724 kilobytes
# => 59,920 kilobytes
# => 60,844 kilobytes
# => 60,156 kilobytes
# => 64,408 kilobytes
# => 67,520 kilobytes
# => 66,960 kilobytes
# => 70,604 kilobytes
# => 74,948 kilobytes
# => 76,040 kilobytes
# => 75,472 kilobytes
# => 76,280 kilobytes
# => 75,528 kilobytes
# => 79,584 kilobytes
```

If you call `.value` on the future when you make it, growth is contained:

``` ruby
puts(Process.pretty_rss)
20.times do
  f = Foo.new
  futures = []
  100.times { futures << f.future.do_something("a" * 50_000).value }
  f.terminate()
  futures = []
  puts(Process.pretty_rss)
end

# => 80,384 kilobytes
# => 79,728 kilobytes
# => 80,536 kilobytes
# => 79,912 kilobytes
# => 80,720 kilobytes
# => 80,124 kilobytes
# => 80,932 kilobytes
# => 80,308 kilobytes
# => 79,756 kilobytes
# => 80,564 kilobytes
# => 79,940 kilobytes
# => 80,748 kilobytes
# => 80,124 kilobytes
# => 80,932 kilobytes
# => 80,308 kilobytes
# => 79,756 kilobytes
# => 80,492 kilobytes
# => 80,036 kilobytes
# => 80,844 kilobytes
# => 80,220 kilobytes
```

Edited by @niamster: test case with a proof https://gist.github.com/niamster/7bbc8a0fcde30f122327

**Comment by sb8244** [comment]
If you put a GC.start after `futures = []` the memory growth seems to halt the growth. Here are my results with repeat = 80 and future calls = 300

It seems to me like it is an issue with how often GC calls rather than something Celluloid is doing.

```
15,120 kilobytes
20,300 kilobytes
25,136 kilobytes
30,364 kilobytes
30,404 kilobytes
30,488 kilobytes
30,488 kilobytes
30,548 kilobytes
30,592 kilobytes
30,592 kilobytes
30,592 kilobytes
30,596 kilobytes
30,596 kilobytes
30,596 kilobytes
30,604 kilobytes
30,652 kilobytes
30,656 kilobytes
30,656 kilobytes
30,656 kilobytes
30,656 kilobytes
30,656 kilobytes
30,976 kilobytes
30,976 kilobytes
30,976 kilobytes
34,472 kilobytes
34,472 kilobytes
34,472 kilobytes
34,472 kilobytes
35,748 kilobytes
35,748 kilobytes
35,748 kilobytes
35,748 kilobytes
35,748 kilobytes
35,748 kilobytes
35,748 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,752 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,756 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
35,764 kilobytes
```

**Comment by jonhyman** [comment]
I had tried that at some point but it doesn't always work. I'm not at a computer but it may be that if you use more strings or increase the size by a factor of 10, it doesn't work. I had updated my application to add the GC.start but it didn't help.

**Comment by jonhyman** [comment]
I don't remember the exact situation but that wasn't a silver bullet in practice.

**Comment by sb8244** [comment]
@unakatsuo I believe that is because when you do `Foo.new` inside of the loop, you are creating 200 actors whereas you only create 1 actor with it outside of the loop. Correct me if I'm wrong, but I believe each actor is 1 thread and can only process 1 message at a time, this means the code is not equivalent. One will run 200 threads and process as simultaneously as the processor allows and one will run 1 thread and do it sequentially.

**Comment by niamster** [comment]
While investigating a "memory" leak in DCell I've found an interesting discussion on ruby forum regarding the leak of the fiber stacks. 
If I understand correctly the culprit is in fact glibc. Ruby itself correctly releases memory used for fiber stack but the memory allocation library does not release it back the the OS. 
I didn't dig into the details but it sounds a little bit strange for me as I was expecting glibc(that's what I have on my linux box) would use mmap/munmap to manage such big chunks. Maybe ruby is not requesting exactly 4K so it doesn't fall into that use case.
Anyway, during my tests I saw that DCell server application started to use enormous amount of memory(~700MB) at some point when I was using glibc for malloc(which is by default).
When I switched to jemalloc, initially the RSS values were higher than with glibc(but in the end the resident memory usage was balancing at about ~100MB.
Some numbers:

measure point | glibc/malloc(2.21) | jemalloc(3.6)
------------------ | ---------------------- | ----------------
before test | 31MB | 79MB
after test | 500MB | 233MB

Test case: one DCell actor, 10 times spawn 500 clients which send about 200 msgs each
The other leak in case of jemalloc might be caused by the issue #495 as in current DCell implementation it's spawn 2 actors per client node. In the end of the test it results in 10_000 floating actors.

Also a "side effect" of using jemalloc was significant performance boost.
Probably this might be suggested to Celluloid users with long living application as Celluloid is using fibers for practically everything.

**Comment by niamster** [comment]
Just for info, I've found a stupid trick to w/a issue #495 that saved a bit of memory: delete all actor instance variable in actor finalizer. After rerunning the test with jemalloc I've got 127MB of RSS for the DCell server node.

**Comment by tarcieri** [comment]
@niamster did removing all the instance variables have any effect on #495?

**Comment by niamster** [comment]
@tarcieri unfortunately it does not help =(

**Comment by niamster** [comment]
I did a quick test and the issue might be rephrased as any arg or and local variable of sync/async/future actor method invocation are not GC'ed.
That's scary, see https://gist.github.com/niamster/7bbc8a0fcde30f122327 as a test case.

**Comment by digitalextremist** [comment]
Thanks for the updated repro and refocusing @niamster. I'm seeing the test case never quit under `mri-2.1.2` but with `jruby-1.7.19` it won't run, stating the `.start` arguments are incorrect: (1 for 0)

**Comment by niamster** [comment]
I've update the gist to make the test case work with jruby and rbx.
Issue is present with rbx-2.5.2, jruby-1.71, mri 1.9.3 and 2.2.0.
Once the line 'include celluloid' is commented out the test is passed with all engines listed above.
Seems like it's really linked to celluloid. Otherwise it would be extremely strange that all implementation suffer from the same issue. I've also tried to use `Celluloid.task_class = Celluloid::TaskThread` and got the same behaviour.

**Comment by digitalextremist** [comment]
I see this issue reproduced in `jruby-1.7.19` now, with your new repro.

**Comment by niamster** [comment]
Just to be sure I've tried to run the test with plain ruby fibers and threads but without celluloid. The test passes.
What is interesting is that if I launch the test inside the ruby fiber or thread, local variable of the Test#foo is properly destroyed, yet the arg is still floating somewhere.

**Comment by digitalextremist** [comment]
@niamster since you are spun-up on this, will you take it as an assignment until it's finished?

**Comment by digitalextremist** [comment]
:+1: @niamster this sounds like an adventure :)

**Comment by niamster** [comment]
I fact all arguments and local instances of the callee are properly destroyed once Celluloid does a context switch. I'm digging further to see if it's feasible to unlink Celluloid:Call once it's done w/o introducing additional complexity. Otherwise we can put an errata to avoid further confusion.

**Comment by digitalextremist** [comment]
@niamster, is there a way for the repro to reflect that, or is this `wontfix/notanissue` because the repro is not in fact hemorrhaging memory any more -- even though it fails to quit?

**Comment by niamster** [comment]
yes, I've updated the gist: https://gist.github.com/niamster/7bbc8a0fcde30f122327

**Comment by digitalextremist** [comment]
With the new repro, the output happens AFTER the process is killed -- in both `rbx` and `jruby`

**Comment by digitalextremist** [comment]
In `mri` it does output before exit, in `jruby` and `rbx` the process must be given `SIGINT` to display output ( which is appropriate output though )

**Comment by digitalextremist** [comment]
@niamster so what have we learned by this? More importantly, is memory usage increasing or decreasing as it is supposed to be?

**Comment by niamster** [comment]
@digitalextremist as we've discussed on IRC indeed rbx and jruby don't behave in the same way as MRI. I'm going to dig further to understand the implementation of GC of the "unofficial" ruby implementations and will try to come with a proper universal solution.

**Comment by digitalextremist** [comment]
This may have to do with the output buffer behavior of Celluloid in those RVM's though, so watch for that also.

**Comment by digitalextremist** [comment]
But I would think it would still terminate by itself even if the output buffer dumps after it self-terminates.

**Comment by tarcieri** [comment]
I'm wondering if it has to do with things being memoized in `InternalPool`, and if whether ditching `InternalPool` entirely would help solve a lot of memory leaks people seem to be experiencing.

**Comment by digitalextremist** [comment]
I will trace the ramifications of removing `InternalPool`

I've seen a lot of run-away memory leaks in my own Celluloid implementations, which fall mysteriously outside what I can affect by changing individual Actor behaviors.

My first thought though -- futures? What context to those run in if not `InternalPool`?

**Comment by tarcieri** [comment]
Futures run inside of the recipient actor, unless you're using the `Celluloid::Future.new { ... }` syntax which can just run them inside a newly spawned thread.

**Comment by digitalextremist** [comment]
Right, I'm talking about the class method route -- I'm good with a la carte threads there, for sure. I will look into this and ticket it as a potential refactor being researched first.

**Comment by niamster** [comment]
In case of rbx I get test passed when I issue yet another ctx switch. In case of jruby I just had to put a little bit more pressure on memory and remove sleep from the loop. I've update the gist(rev. 10)

**Comment by niamster** [comment]
Basically last sent messages by both caller and callee are still linked. I have a fear that some block(a closure) is still holding a reference to them. I still didn't spot which one though. 
So far I see that after the call to the Cell::task method the reference to Celluloid::Call is released.
A dumb w/a would be to clean Celluloid::Call and Celluloid::Response instance variables when they are actually not needed. This at least releases the resources of the call arguments and return value.

**Comment by digitalextremist** [comment]
@niamster I believe this is fixed in #545. Still having that output buffer issue with `rbx` and `jruby` thought.

**Comment by niamster** [comment]
@digitalextremist unfortunately it's fixed in 0-16-5-prerelease.
I see that the call stack of the callee thread of fiber is not properly unwounded. Some blocks are still hanging and hold references to the message. I don't understand why it happens, maybe some subtle Ruby bug.
ATM I'm trying to understand why this happens.

**Comment by niamster** [comment]
@digitalextremist in fact the test is passed with `Celluloid::Task::Threaded` but not with Fibered.
Though I've found one "feature" of fiber and when it's applied the problem goes away.
The issue is illustrated here: https://gist.github.com/niamster/862acd8a0c2561940ffc
I'm going to brainstorm this on stackoverflow but maybe you already can give the explanation of this phenomenon.
Thus I'm preparing a fix for this.

**Comment by niamster** [comment]
@digitalextremist argh, it was too early to scream about the fix. In fact it's "fixed" only with my additional changes which I find quite intrusive. Let me settle with a complete solution here.

**Comment by digitalextremist** [comment]
@niamster do you mind gisting those intrusive fixes so I can understand the problem, while you polish off a more elegant solution? Thanks for your work on this.

Wait! Given your example, what if we always called `yield` on an empty proc/block? Basically, what if we wrap `Fiber` or override it? Would that be performant and yet solve the issue?

**Comment by niamster** [comment]
@digitalextremist there's nothing much to share. I've tried to eliminate blocks on the call path and properly terminate the fiber: niamster/celluloid@0dcd0f9 and niamster/celluloid@b204571. There's still some problems with Timers::Wait.for in mailbox.rb that I didn't handle and they reference the call result.
If you turn those Timers::Wait.for blocks into `while true ... end` the call result is properly released as well. 
IMHO this is all is a nasty workaround. Do you have idea why the procs are not properly unreferenced?

**Comment by digitalextremist** [comment]
This goes back to `2009` and describes what I see:

* https://www.ruby-forum.com/topic/191985

> In general, however, you're not guaranteed that finalizers will be called at any point-- *only guaranteed that they'll be called before the program exits* (I think that's what happens anyway).

It was supposed to be handled in `1.9` but, yeah... no.

Thank you for your research and I will be looking at this too.

**Comment by niamster** [comment]
@digitalextremist thanks for the reference.
This is a more subtle problem though seems like present only in MRI(2.2 here). Jruby doesn't have it.
I've been looking at actor leak(#495) and in fact it's not only linked to dangling blocks but also to proxies. Here's a minimal illustration of the leak: https://gist.github.com/niamster/e050dbee1ace792d126b

**Comment by tarcieri** [comment]
@niamster it'd be good to get your memory leak tests into Celluloid proper, if only in pending form right now because they're presently failing

**Comment by niamster** [comment]
@tarcieri I can't state that those are purely celluloid. Some of the leaks are linked purely to MRI(method-missing test(my comment just above) passes fine with rbx and jruby).

**Comment by tarcieri** [comment]
@niamster even if there's platform specific errata, we should make sure to check if we're causing leaks, and if we do want to declare defeat for a specific platform we can disable the check for that platform.

**Comment by niamster** [comment]
@tarcieri I find MRI's GC so non-deterministic but I agree some test cases should be documented in the spec.

**Comment by niamster** [comment]
If smbd is still curios what's happening here I've found out that at least in MRI the value passed to return or break within a block are always(well, 99%) leaked.
With a minimal patch I could avoid the leak of the method return value in MRI though it still not collected in jruby nor in rbx.
Unfortunately the MRI's objspace module doesn't give any more valuable hints(those don't make any sense).

**Comment by e2** [comment]
@niamster - very interesting, thanks.

**Comment by curtislinden** [comment]
I'm wondering on the status of this... We have a shoryuken process that grows slowly over the day and then hits our high memory mark in docker daily. 

I'm suspecting that this issue in celluloid is connected. I'm not sure how we might verify this. 

Any thoughts?

**Comment by niamster** [comment]
Fixed few memory leaks in mri and jruby: #584
@curtislinden how are you using actors? Do you create them quite often? Which ruby implementation are you using?

**Comment by curtislinden** [comment]
@niamster  We are using Shoryuken which is using 'async' faculty, they get created for every queue entry in SQS. We have the issue daily - i've set docker to top out memory to that process at 500mb and then to always restart it as a workaround.

I've used ruby mri 2.2.1, mri 2.1.5 and jruby 9.0.0.0.pre1. Memory starts at 120mb and grows to 500mb over about 6-8 hours or about 2000 queue entries

**Comment by niamster** [comment]
@curtislinden try to delete actor instance variables in the celluloid finalizer. The "celluloized" object is known to be never collected by GC.
You may check a w/a for DCell: niamster/dcell@61d4e0d919ae702df22dc9472aec57f5d7aa32ee

**Comment by digitalextremist** [comment]
Unless this is magically solved now/today, I'm moving this to `0.17.5`

**Comment by texpert** [comment]
Maybe this is causing leaks? https://evilmartians.com/chronicles/ruby-2_2-oom

**Comment by curtislinden** [comment]
oh yeah good find. Could be related - this was pre 2.2.2 however.

On Mon, Dec 28, 2015 at 12:17 PM, Aurel Branzeanu <notifications@github.com>
wrote:

> Maybe this is causing leaks?
> https://evilmartians.com/chronicles/ruby-2_2-oom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/celluloid/celluloid/issues/463#issuecomment-167645212>
> .
>



-- 
Curtis J Schofield | Senior Systems Analyst | U2U
Skype robotarmymade | Second Life Curtis Linden | C 415.632.6001

Linden Lab | Makers of Shared Creative Spaces

**Comment by marshall-lee** [comment]
@texpert reproduction code contains neither recursion nor deep method calls, so i think no.

**Comment by tboyko** [comment]
I believe that I am still seeing this issue with `0.17.3` and MRI. Thought I was going crazy until I found this thread! In our use case, we are instantiating many Actors over time (and terminating) so that we have a constant "alive" number of actors. 

I've implemented the suggestion by @niamster to dereference instance variables in a finalizer, but this is just a partial workaround. Is there any way to explicitly mark the actor or "celluloidized object" for garbage collection?

Our alternative is to used a fixed number of Actor objects and essentially rerun initialization-like behaviors as opposed to killing one off and creating a new one. This is OK, but requires some messier code, and use of a Mutex and ConditionVariable for signalling (so we don't reinitialize while `.async` operations are occurring).

FWIW, I did not see this issue in an earlier implementation of our same project which ran Celluloid `0.16.0` requiring `celluloid` instead of `celluloid/current`.
